name: Test
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [
          ubuntu-latest,
          macos-latest,
          windows-latest,
        ]
        toolchain: [
          stable,
        ]
        features: [
          '',
          '--no-default-features',
          '--no-default-features --features serde',
          '--no-default-features --features serde,std,serde_std',
          '--no-default-features --features std,futures-io',
          '--no-default-features --features std,tokio',
          '--no-default-features --features std,tokio,futures-io',
          '--no-default-features --features std,tokio,serde,serde_std',
        ]
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: ${{ matrix.toolchain }}

      - name: Cargo Test
        uses: actions-rs/cargo@v1
        env:
          RUST_BACKTRACE: 1
        with:
          command: test
          args: ${{ matrix.features }}
