name: Static Analysis
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  static-analysis:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [
          ubuntu-latest,
        ]
        toolchain: [
          stable,
        ]
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Rust Toolchain
        run: |
          rustup toolchain install ${{ matrix.toolchain }} --profile minimal --no-self-update
          rustup default ${{ matrix.toolchain }}

      - name: Rust Cache
        uses: Swatinem/rust-cache@v2

      - name: Make Static
        run: make static
